[package]
authors = ["myuon <ioi.joi.koi.loi@gmail.com>"]
edition = "2018"
name = "rustapp-example"
version = "0.1.0"
[dependencies]
actix-web = "1.0.8"
dotenv = "*"
r2d2 = "*"

[dependencies.diesel]
features = ["mysql"]
version = "1.4.2"
